#ifndef PLAYER_FFMPEG_VIDEO_FFMPEG_ECPORT_H_
#define PLAYER_FFMPEG_VIDEO_FFMPEG_ECPORT_H_
#include <QtCore/QObject>

#if defined(PLAYER_FFMPEG_DLL)
#  define PLAYER_FFMPEG_API Q_DECL_EXPORT
#else
#  define PLAYER_FFMPEG_API Q_DECL_IMPORT
#endif

#endif // PLAYER_FFMPEG_VIDEO_FFMPEG_ECPORT_H_
