#ifndef _NESTPLACER_EXPORT_H
#define _NESTPLACER_EXPORT_H
#include "ccglobal/export.h"

#if USE_NESTPLACER_DLL
#define NESTPLACER_API CC_DECLARE_IMPORT
#elif USE_NESTPLACER_STATIC
#define NESTPLACER_API CC_DECLARE_STATIC
#else
#if NESTPLACER_DLL
#define NESTPLACER_API CC_DECLARE_EXPORT
#else
#define NESTPLACER_API CC_DECLARE_STATIC
#endif
#endif

#endif
