#ifndef CADCORE_INTERFACE_1604911737496_H
#define CADCORE_INTERFACE_1604911737496_H

#include "ccglobal/export.h"

#if USE_CADCORE_DLL
	#define CADCORE_API CC_DECLARE_IMPORT
#elif USE_CADCORE_STATIC
	#define CADCORE_API CC_DECLARE_STATIC
#else
	#if CADCORE_DLL
		#define CADCORE_API CC_DECLARE_EXPORT
	#else
		#define CADCORE_API CC_DECLARE_STATIC
	#endif
#endif

#endif // CADCORE_INTERFACE_HPP_

