#ifndef MESH_BASE_INTERFACE_1604911737496_H
#define MESH_BASE_INTERFACE_1604911737496_H
#include "ccglobal/export.h"

#if USE_MSBASE_DLL
	#define MSBASE_API CC_DECLARE_IMPORT
#elif USE_MSBASE_STATIC
	#define MSBASE_API CC_DECLARE_STATIC
#else
	#if MSBASE_DLL
		#define MSBASE_API CC_DECLARE_EXPORT
	#else
		#define MSBASE_API CC_DECLARE_STATIC
	#endif
#endif

#endif // MESH_BASE_INTERFACE_1604911737496_H