#ifndef TOPOMESH_INTERFACE_1604911737496_H
#define TOPOMESH_INTERFACE_1604911737496_H
#include "ccglobal/export.h"

#if USE_TOPOMESH_DLL
	#define TOPOMESH_API CC_DECLARE_IMPORT
#elif USE_TOPOMESH_STATIC
	#define TOPOMESH_API CC_DECLARE_STATIC
#else
	#if TOPOMESH_DLL
		#define TOPOMESH_API CC_DECLARE_EXPORT
	#else
		#define TOPOMESH_API CC_DECLARE_STATIC
	#endif
#endif

#endif // TOPOMESH_INTERFACE_1604911737496_H