#ifndef QXPOTRACE_GLOBAL_H
#define QXPOTRACE_GLOBAL_H

#include <QtGlobal>

#if defined(QXPOTRACE_LIBRARY)
#  define QXPOTRACE_EXPORT Q_DECL_EXPORT
#else
#  define QXPOTRACE_EXPORT Q_DECL_IMPORT
#endif

#endif // QXPOTRACE_GLOBAL_H
