#ifdef WIN32
    // Why?
    #define _WIN32_WINNT 0x0502
    // The standard Windows includes.
    #define WIN32_LEAN_AND_MEAN
    #define NOMINMAX
    #include <Windows.h>
    #include <wchar.h>
#endif /* WIN32 */
#ifdef _MSC_VER
#include <new.h>
// MSVC-sized new-handler adapter: capture requested allocation size without allocating/logging here.
static _PNH g_cp_prev_new_handler_pnh = nullptr;
static thread_local size_t g_cp_last_new_req_size = 0;
static int __cdecl g_cp_sized_new_handler_adapter(size_t bytes) noexcept {
    g_cp_last_new_req_size = bytes; // record for later logging in the void-handler
    _PNH prev = g_cp_prev_new_handler_pnh;
    if (prev) return prev(bytes);   // delegate to existing handler (installed by std::set_new_handler)
    return 0;                       // no previous handler: fail without retry
}
#endif

#include <cstdio>
#include <ctime>
#include <string>
#include <cstring>
#include <iostream>
#include <fstream>
#include <memory>
#include <math.h>

#if defined(__linux__) || defined(__LINUX__)
#include <condition_variable>
#include <mutex>
#include <boost/thread.hpp>
//add json logic
#include "nlohmann/json.hpp"
#include <unistd.h>
#include <dirent.h>
#include <sys/wait.h>
#include <climits>

using namespace nlohmann;
#endif

#include <boost/algorithm/string/predicate.hpp>
#include <boost/filesystem.hpp>
#include <boost/nowide/args.hpp>
#include <boost/nowide/cenv.hpp>
#include <boost/nowide/iostream.hpp>
#include <boost/nowide/fstream.hpp>
#include <boost/nowide/integration/filesystem.hpp>
#include <boost/dll/runtime_symbol_info.hpp>
#include <boost/log/trivial.hpp>

#include "unix/fhs.hpp"  // Generated by CMake from ../platform/unix/fhs.hpp.in

#include "libslic3r/libslic3r.h"
#include "libslic3r/Config.hpp"
#include "libslic3r/Geometry.hpp"
#include "libslic3r/GCode/PostProcessor.hpp"
#include "libslic3r/Model.hpp"
#include "libslic3r/ModelInstance.hpp"
#include "libslic3r/ModelVolume.hpp"
#include "libslic3r/ModelArrange.hpp"
#include "libslic3r/Platform.hpp"
#include "libslic3r/Print.hpp"
#include "libslic3r/SLAPrint.hpp"
#include "libslic3r/TriangleMesh.hpp"
#include "libslic3r/Format/AMF.hpp"
#include "libslic3r/Format/3mf.hpp"
#include "libslic3r/Format/SL1.hpp"
#include "libslic3r/Utils.hpp"
#include "libslic3r/Time.hpp"
#include "libslic3r/Thread.hpp"
#include "libslic3r/BlacklistedLibraryCheck.hpp"
#include "libslic3r/FlushVolCalc.hpp"
#include "libslic3r/BuildVolume.hpp"
#include "libslic3r/PresetConfigCache.hpp"
#include "cr_km_recipe.h"

#include "slic3r/CLI/CLI.hpp"
//BBS: add exception handler for win32
#include <wx/stdpaths.h>
#include <wx/filename.h>
#include <wx/utils.h>

#ifdef WIN32
#include "BaseException.h"
#include "CxMiniDump.h"
#include "libslic3r/UnittestFlow.hpp"
#include <stdlib.h>  // _set_invalid_parameter_handler
    #ifdef USE_BREAKPAD
    #include "client/windows/handler/exception_handler.h"
    #endif
#endif

static std::string get_cpu_model_string()
{
#ifdef WIN32
    constexpr DWORD bufsize_ = 500;
    DWORD           bufsize  = bufsize_ - 1;
    char            buf[bufsize_] = "";
    memset(buf, 0, sizeof(buf));
    const std::string reg_path = "HARDWARE\\DESCRIPTION\\System\\CentralProcessor\\0";
    if (RegGetValueA(HKEY_LOCAL_MACHINE, reg_path.c_str(), "ProcessorNameString",
        RRF_RT_REG_SZ, NULL, &buf, &bufsize) == ERROR_SUCCESS) {
        return std::string(buf);
    }
#endif
    return std::string();
}





#ifdef __WXGTK__
#include <wx/glcanvas.h>
#include <X11/Xlib.h>
#endif

#ifdef SLIC3R_GUI
    #include "slic3r/GUI/GUI_Init.hpp"
#endif /* SLIC3R_GUI */
#if defined(__linux__) || defined(__LINUX__)
    #ifndef __STDC_FORMAT_MACROS
        #define __STDC_FORMAT_MACROS
    #endif
    #ifdef USE_BREAKPAD
    #include "client/linux/handler/exception_handler.h"
    #endif
#endif


using namespace Slic3r;



struct ApplicationArguments
{
    bool cli_mode {false};
    std::vector<char *> forwarded;

    int argc() const { return static_cast<int>(forwarded.size()) - 1; }
    char **argv() { return forwarded.data(); }
};

static ApplicationArguments parse_application_arguments(int argc, char **argv)
{
    ApplicationArguments result;
    result.forwarded.reserve(static_cast<size_t>(argc) + 1);
    if (argc > 0)
        result.forwarded.push_back(argv[0]);

    for (int index = 1; index < argc; ++index) {
        if (std::strcmp(argv[index], "--cli") == 0) {
            result.cli_mode = true;
            continue;
        }
        result.forwarded.push_back(argv[index]);
    }
    result.forwarded.push_back(nullptr);
    return result;
}

static void initialize_application_environment()
{
    detect_platform();

#ifdef WIN32
    if (BlacklistedLibraryCheck::get_instance().perform_check()) {
        std::wstring message = L"Following DLLs have been injected into the CrealityPrint process:\n\n";
        message += BlacklistedLibraryCheck::get_instance().get_blacklisted_string();
        message += L"\n\n"
                   L"CrealityPrint is known to not run correctly with these DLLs injected. "
                   L"We suggest stopping or uninstalling these services if you experience "
                   L"crashes or unexpected behaviour while using CrealityPrint.\n"
                   L"For example, ASUS Sonic Studio injects a Nahimic driver, which makes "
                   L"CrealityPrint crash on a secondary monitor.";
        MessageBoxW(nullptr, message.c_str(), L"Warning", MB_OK);
    }
#endif

    const boost::filesystem::path executable = boost::dll::program_location();
#ifdef __APPLE__
    const boost::filesystem::path resources =
        boost::filesystem::canonical(executable).parent_path().parent_path() / "Resources";
#elif defined _WIN32
    const boost::filesystem::path resources = executable.parent_path() / "resources";
#elif defined SLIC3R_FHS
    const boost::filesystem::path resources = SLIC3R_FHS_RESOURCES;
#else
    const boost::filesystem::path resources =
        boost::filesystem::canonical(executable).parent_path().parent_path() / "resources";
#endif

    set_resources_dir(resources.string());
    // Closed-source K-M recipe library reads base_color_spectra.json from
    // <resources>/filament_mixing/ at runtime. Forward the same path so both
    // layers see the same data set.
    cr_close_set_resources_dir(resources.string().c_str());
    set_var_dir((resources / "images").string());
    set_local_dir((resources / "i18n").string());
    set_sys_shapes_dir((resources / "shapes").string());
    set_custom_gcodes_dir((resources / "custom_gcodes").string());
    set_temporary_dir(wxFileName::GetTempDir().utf8_str().data());
}

static int run_application(int argc, char **argv)
{
    struct PendingPresetCacheWritesGuard {
        ~PendingPresetCacheWritesGuard()
        {
            Slic3r::PresetConfigCache::wait_for_pending_writes();
        }
    } pending_preset_cache_writes_guard;

    ApplicationArguments arguments = parse_application_arguments(argc, argv);

    set_current_thread_name("crealityprint_main");
    save_main_thread_id();

#ifdef __WXGTK__
    const char *wayland_display = ::getenv("WAYLAND_DISPLAY");
    const char *session_type = ::getenv("XDG_SESSION_TYPE");
    const char *gdk_backend = ::getenv("GDK_BACKEND");
    const bool is_wayland =
        (gdk_backend != nullptr && ::strcmp(gdk_backend, "wayland") == 0) ||
        (gdk_backend == nullptr &&
         ((wayland_display && *wayland_display) ||
          (session_type && ::strcmp(session_type, "wayland") == 0)));

    // WebKit accelerated compositing can leave overlapping or unresponsive
    // child surfaces when switching between WebViews and the 3D page on
    // native Wayland. Set this before GTK/WebKit initialization and child
    // process creation; keep X11 and explicit launcher settings unchanged.
    if (is_wayland)
        ::setenv("WEBKIT_DISABLE_COMPOSITING_MODE", "1", /* overwrite */ false);

    auto has_multiple_drm_render_nodes = []() {
        int count = 0;
        if (DIR *dir = ::opendir("/dev/dri")) {
            while (dirent *entry = ::readdir(dir)) {
                if (::strncmp(entry->d_name, "renderD", 7) == 0 && ++count > 1)
                    break;
            }
            ::closedir(dir);
        }
        return count > 1;
    };
    if (has_multiple_drm_render_nodes())
        ::setenv("DRI_PRIME", "1", false);

    if (::access("/proc/driver/nvidia/version", F_OK) == 0) {
        ::setenv("__NV_PRIME_RENDER_OFFLOAD", "1", false);
        if (!is_wayland)
            ::setenv("__GLX_VENDOR_LIBRARY_NAME", "nvidia", false);
    }

    if (!is_wayland) {
        XInitThreads();
#if wxCHECK_VERSION(3, 3, 0)
        wxGLCanvas::PreferGLX();
#endif
    }

    BOOST_LOG_TRIVIAL(info) << "Display server: " << (is_wayland ? "Wayland" : "X11");
#endif

    try {
        boost::nowide::nowide_filesystem();
    } catch (const std::runtime_error &error) {
        const std::string caption = std::string(SLIC3R_APP_FULL_NAME) + " Error";
        const std::string message =
            std::string("boost::nowide::nowide_filesystem Failed!\n") +
            SLIC3R_APP_FULL_NAME + " will now terminate.\n\n" + error.what();
#if defined(_WIN32) && defined(SLIC3R_GUI)
        MessageBoxA(nullptr, message.c_str(), caption.c_str(), MB_OK | MB_ICONERROR);
#endif
        boost::nowide::cerr << message << std::endl;
        return CLI_ENVIRONMENT_ERROR;
    }

    initialize_application_environment();

    if (arguments.cli_mode) {
        BOOST_LOG_TRIVIAL(info) << "launch mode: CLI";
        return CLI::run(arguments.argc(), arguments.argv());
    }

#ifdef SLIC3R_GUI
    BOOST_LOG_TRIVIAL(info) << "launch mode: GUI";
    return GUI::GUI_Run(arguments.argc(), arguments.argv());
#else
    boost::nowide::cerr << "GUI mode is unavailable in this build" << std::endl;
    return CLI_UNSUPPORTED_OPERATION;
#endif
}
//BBS: dump stack debug codes, don't delete currently
//#include <dbghelp.h>
//#pragma comment(lib, "version.lib")
//#pragma comment( lib, "dbghelp.lib" )
/*DWORD main_thread_id;
std::string TraceStack()
{
    static const int MAX_STACK_FRAMES = 16;

    void* pStack[MAX_STACK_FRAMES];

    HANDLE process = GetCurrentProcess();
    SymInitialize(process, NULL, TRUE);
    WORD frames = CaptureStackBackTrace(0, MAX_STACK_FRAMES, pStack, NULL);

    std::ostringstream oss;
    oss << "stack traceback: frames="<< frames << std::endl;
    for (WORD i = 0; i < frames; ++i) {
        DWORD64 address = (DWORD64)(pStack[i]);

        DWORD64 displacementSym = 0;
        char buffer[sizeof(SYMBOL_INFO) + MAX_SYM_NAME * sizeof(TCHAR)];
        PSYMBOL_INFO pSymbol = (PSYMBOL_INFO)buffer;
        pSymbol->SizeOfStruct = sizeof(SYMBOL_INFO);
        pSymbol->MaxNameLen = MAX_SYM_NAME;

        DWORD displacementLine = 0;
        IMAGEHLP_LINE64 line;
        //SymSetOptions(SYMOPT_LOAD_LINES);
        line.SizeOfStruct = sizeof(IMAGEHLP_LINE64);

        if (SymFromAddr(process, address, &displacementSym, pSymbol)
            && SymGetLineFromAddr64(process, address, &displacementLine, &line)) {
            oss << "\t" << pSymbol->Name << " at " << line.FileName << ":" << line.LineNumber << "(0x" << std::hex << pSymbol->Address << std::dec << ")" << std::endl;
        }
        else {
            oss << "\terror: " << GetLastError() << std::endl;
        }
    }
    return oss.str();
}

LONG WINAPI VectoredExceptionHandler(PEXCEPTION_POINTERS pExceptionInfo)
{
    std::ofstream f;

    DWORD cur_thread_id = GetCurrentThreadId();
    f.open("VectoredExceptionHandler.txt", std::ios::out | std::ios::app);
    f << "main thread id="<<main_thread_id<<", current thread_id="<< cur_thread_id << std::endl;
    f << std::hex << pExceptionInfo->ExceptionRecord->ExceptionCode << std::endl;
    f << TraceStack();
    f.flush();
    f.close();

    return EXCEPTION_CONTINUE_SEARCH;
}*/

// ---- Enhanced CRT invalid-parameter stack capture ----
// When CRT detects an invalid parameter (e.g. NULL passed to printf/sprintf),
// it invokes _invalid_parameter_handler as a plain C callback, NOT an SEH exception.
// Breakpad's default handler generates a minidump in this callback, but the resulting
// dump often has an incomplete stack because the callback context doesn't carry proper
// EXCEPTION_POINTERS for reliable unwinding.
//
// This handler runs BEFORE Breakpad: it calls CaptureStackBackTrace (which uses the
// OS-level .pdata unwind info and is very reliable on x64) to capture the full call
// chain while all caller frames are still intact, writes module+RVA for every frame
// to a log file, then chains to Breakpad's handler so the dump is still generated.
//
// To resolve addresses offline:
//   symbol = PDB_lookup(module_name, RVA)
//   e.g.  CrealityPrint_Slicer.DLL + 0x00123456  ->  look up RVA 0x00123456 in PDB
#if defined(WIN32) && defined(USE_BREAKPAD)
static _invalid_parameter_handler g_prev_invalid_param_handler = nullptr;
static volatile LONG              g_in_invalid_param_handler   = 0;

static void __cdecl CrealityInvalidParameterHandler(
    const wchar_t* expression,
    const wchar_t* function,
    const wchar_t* file,
    unsigned int   line,
    uintptr_t      pReserved)
{
    // Re-entrancy guard: if we somehow trigger another invalid-parameter inside
    // this handler, skip straight to Breakpad to avoid infinite recursion.
    if (InterlockedCompareExchange(&g_in_invalid_param_handler, 1, 0) != 0) {
        if (g_prev_invalid_param_handler)
            g_prev_invalid_param_handler(expression, function, file, line, pReserved);
        return;
    }

    // 1. Capture full stack backtrace -- all caller frames are still intact at this point.
    enum { kMaxFrames = 128 };
    void*  stackFrames[kMaxFrames];
    USHORT frameCount = CaptureStackBackTrace(0, kMaxFrames, stackFrames, NULL);

    // 2. Write to a log file in temp dir, using only Win32 API to avoid CRT re-entrance.
    wchar_t logPath[MAX_PATH] = {0};
    GetTempPathW(MAX_PATH, logPath);
    lstrcatW(logPath, L"crealityprint_invalid_param_stack.log");

    HANDLE hFile = CreateFileW(logPath, FILE_APPEND_DATA,
                               FILE_SHARE_READ | FILE_SHARE_WRITE,
                               NULL, OPEN_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
    if (hFile != INVALID_HANDLE_VALUE) {
        char  buf[512];
        DWORD written = 0;
        int   len     = 0;

        // Header with timestamp and thread ID
        SYSTEMTIME st;
        GetLocalTime(&st);
        len = wsprintfA(buf,
            "\r\n=== InvalidParameter [%04d-%02d-%02d %02d:%02d:%02d] TID=%lu ===\r\n",
            st.wYear, st.wMonth, st.wDay, st.wHour, st.wMinute, st.wSecond,
            GetCurrentThreadId());
        WriteFile(hFile, buf, (DWORD)len, &written, NULL);

        len = wsprintfA(buf, "Frames: %d\r\n", (int)frameCount);
        WriteFile(hFile, buf, (DWORD)len, &written, NULL);

        // Each frame: absolute address, module short name, RVA
        for (USHORT i = 0; i < frameCount; ++i) {
            HMODULE hMod = NULL;
            char    modPath[MAX_PATH];
            modPath[0] = '\0';

            if (GetModuleHandleExA(
                    GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS |
                    GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                    (LPCSTR)stackFrames[i], &hMod) && hMod) {
                GetModuleFileNameA(hMod, modPath, MAX_PATH);
            }

            // Find short module name (after last path separator)
            const char* shortName = modPath;
            for (const char* p = modPath; *p != '\0'; ++p) {
                if (*p == '\\' || *p == '/')
                    shortName = p + 1;
            }
            if (*shortName == '\0')
                shortName = "<unknown>";

            ULONG_PTR rva = hMod ? ((ULONG_PTR)stackFrames[i] - (ULONG_PTR)hMod) : 0;
            len = wsprintfA(buf, "  [%02d] %p  %s + %p\r\n",
                           (int)i, stackFrames[i], shortName, (void*)rva);
            WriteFile(hFile, buf, (DWORD)len, &written, NULL);
        }

        CloseHandle(hFile);
    }

    InterlockedExchange(&g_in_invalid_param_handler, 0);

    // 3. Delegate to Breakpad's original handler -- dump is generated as usual.
    if (g_prev_invalid_param_handler) {
        g_prev_invalid_param_handler(expression, function, file, line, pReserved);
    }
}
#endif // defined(WIN32) && defined(USE_BREAKPAD)

#if defined(_MSC_VER) || defined(__MINGW32__)
extern "C" {
    __declspec(dllexport) int __stdcall crealityprint_main(int argc, wchar_t **argv)
    {
        BOOST_LOG_TRIVIAL(error) << "crealityprint_main start";
	boost::log::core::get()->flush();
        // Convert wchar_t arguments to UTF8.
        std::vector<std::string> 	argv_narrow;
        std::vector<char*>			argv_ptrs(argc + 1, nullptr);
        for (size_t i = 0; i < argc; ++ i)
            argv_narrow.emplace_back(boost::nowide::narrow(argv[i]));
        for (size_t i = 0; i < argc; ++ i)
            argv_ptrs[i] = argv_narrow[i].data();

//BBS: register default exception handler
#if BBL_RELEASE_TO_PUBLIC
#ifdef USE_BREAKPAD
        //MiniDump::EnableAutoDump(true);
        auto dmpCallBack = [](const wchar_t* dump_path,
                                   const wchar_t* minidump_id,
                                   void* context,
                                   EXCEPTION_POINTERS* exinfo,
                                   MDRawAssertionInfo* assertion,
                                   bool succeeded) -> bool {
            if (succeeded) {
                boost::filesystem::path oldPath(dump_path);
                std::string data_dir = wxStandardPaths::Get().GetUserDataDir().ToUTF8().data();
                //A.0
                const std::string version_dir = Slic3r::data_directory_name();
#ifdef _WIN32
                std::string LogFilePath = data_dir + "\\" + SLIC3R_APP_USE_FORDER + "\\" + version_dir + "\\" + "log";
#else
                std::string LogFilePath = data_dir + "/" + SLIC3R_APP_USE_FORDER + "/" + version_dir + "/" + "log";
#endif
                if (!LogFilePath.empty() && !boost::filesystem::exists(LogFilePath)) {
                    boost::filesystem::create_directories(LogFilePath);
                }
                boost::filesystem::path logPath(LogFilePath);
                oldPath.append(minidump_id).replace_extension(".dmp");

                boost::posix_time::ptime now = boost::posix_time::second_clock::local_time();
                // 创建一个 time_facet 对象，用于自定义时间格式
                boost::posix_time::time_facet* timeFacet = new boost::posix_time::time_facet();
                std::stringstream ss;
                // 设置时间格式为 yyyyMMDD_hhmmss
                timeFacet->format("%Y%m%d_%H%M%S");
                ss.imbue(std::locale(std::locale::classic(), timeFacet));
                ss << now;

                std::string timeStr = ss.str();
                std::string processNameStr = timeStr + std::string("_") +  SLIC3R_PROCESS_NAME + std::string("_") + CREALITYPRINT_VERSION + std::string("_") + PROJECT_VERSION_EXTRA + std::string(".dmp");
                //boost::filesystem::path newPath(dump_path);
                //newPath.append(processNameStr).replace_extension(".dmp");
                logPath.append(processNameStr);
                //MessageBox(NULL, logPath.wstring().c_str(), minidump_id, MB_OK | MB_ICONINFORMATION);

                if (boost::filesystem::exists(oldPath))
                {
                    boost::filesystem::rename(oldPath, logPath);
#ifdef _WIN32
                    std::string cpu_model = get_cpu_model_string();
                    if (!cpu_model.empty()) {
                        std::ofstream ofs(logPath.string(), std::ios::binary | std::ios::app);
                        if (ofs.is_open()) {
                            ofs << "\nCPU_MODEL: " << cpu_model << "\n";
                        }
                    }
#endif
                    wxString command = "%s.exe \"minidump://file=%s\"";
                    command = command.Format(command, SLIC3R_PROCESS_NAME, logPath.wstring().c_str());
                    wxExecute(command, wxEXEC_ASYNC);
                }

                BOOST_LOG_TRIVIAL(info) << "MiniDump succeeded: " << dump_path << ", minidump_id: " << minidump_id;
            }
            else {
                BOOST_LOG_TRIVIAL(error) << "MiniDump failed: " << dump_path << ", minidump_id: " << minidump_id;
            }
            return true;
        };    
#endif

        boost::filesystem::path   tempPath = boost::filesystem::path(wxFileName::GetTempDir().ToStdString());
        if (argc == 2 && boost::starts_with(argv_narrow[1], "minidump://file=")) {
        } else {
             #ifdef USE_BREAKPAD
            google_breakpad::ExceptionHandler* pCrashHandel =
                new google_breakpad::ExceptionHandler(tempPath.wstring(), NULL, dmpCallBack, NULL,
                                                      google_breakpad::ExceptionHandler::HANDLER_ALL, NULL);
            // Enhance CRT invalid-parameter crashes with full stack capture.
            // Chains to Breakpad's handler afterwards so dump is still generated.
            g_prev_invalid_param_handler = _set_invalid_parameter_handler(CrealityInvalidParameterHandler);
             #endif
        }
        
        
        //SET_DEFULTER_HANDLER();
#else
        //AddVectoredExceptionHandler(1, CBaseException::UnhandledExceptionFilter);
        SET_DEFULTER_HANDLER();
#endif
        std::set_new_handler([]() {
            static bool already_in_handler = false;

            if (already_in_handler) {
                already_in_handler = false; // 重置共享的标志位
                throw std::bad_alloc();     // 直接抛出异常返回，防止递归死循环
            }

            already_in_handler = true; // 第一层设置标志位

            // 打印日志（可能触发递归）
            system_memory_stats(__FUNCTION__);
#ifdef _MSC_VER
            // 追加：记录到的本次失败分配请求大小（来自 CRT sized new-handler），便于判断是否异常大块
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << " RequestedNewSize=" << (unsigned long long)g_cp_last_new_req_size;
#endif
#ifdef _WIN32
            // 追加：打印当前进程内存快照（忽略日志级别抑制）
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << " process memory info " << log_memory_info(true);
            // 追加：系统内存状态快照，辅助判断是否接近提交/物理内存上限
            MEMORYSTATUSEX gmsx{};
            gmsx.dwLength = sizeof(gmsx);
            if (GlobalMemoryStatusEx(&gmsx)) {
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__
                                         << " GlobalMemoryStatusEx: MemoryLoad=" << gmsx.dwMemoryLoad
                                         << " TotalPhys=" << (unsigned long long)gmsx.ullTotalPhys
                                         << " AvailPhys=" << (unsigned long long)gmsx.ullAvailPhys
                                         << " TotalPageFile=" << (unsigned long long)gmsx.ullTotalPageFile
                                         << " AvailPageFile=" << (unsigned long long)gmsx.ullAvailPageFile;
            }
            // 追加：进程句柄数（大量句柄泄漏可能导致失败）
            DWORD handle_count = 0;
            if (GetProcessHandleCount(GetCurrentProcess(), &handle_count)) {
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << " HandleCount=" << handle_count;
            }
    #ifdef SLIC3R_GUI
            // 追加：GUI 资源占用（仅 GUI 进程有效）
            DWORD gdi_count  = GetGuiResources(GetCurrentProcess(), GR_GDIOBJECTS);
            DWORD user_count = GetGuiResources(GetCurrentProcess(), GR_USEROBJECTS);
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << " GUIResources: GDI=" << gdi_count << " USER=" << user_count;
    #endif
            // 追加：系统提交信息（更直观的 CommitTotal/CommitLimit），使用动态获取避免包含 <psapi.h>
            typedef struct _MY_PERFORMANCE_INFORMATION {
                DWORD  cb;
                SIZE_T CommitTotal;
                SIZE_T CommitLimit;
                SIZE_T CommitPeak;
                SIZE_T PhysicalTotal;
                SIZE_T PhysicalAvailable;
                SIZE_T SystemCache;
                SIZE_T KernelTotal;
                SIZE_T KernelPaged;
                SIZE_T KernelNonpaged;
                SIZE_T PageSize;
                DWORD  HandleCount;
                DWORD  ProcessCount;
                DWORD  ThreadCount;
            } MY_PERFORMANCE_INFORMATION, *PMY_PERFORMANCE_INFORMATION;
            typedef BOOL (WINAPI *PFN_GetPerformanceInfo)(PMY_PERFORMANCE_INFORMATION, DWORD);
            HMODULE hPsapi = GetModuleHandleW(L"psapi.dll");
            bool psapi_loaded = false;
            if (!hPsapi) { hPsapi = LoadLibraryW(L"psapi.dll"); psapi_loaded = (hPsapi != nullptr); }
            if (hPsapi) {
                auto pGetPerformanceInfo = reinterpret_cast<PFN_GetPerformanceInfo>(GetProcAddress(hPsapi, "GetPerformanceInfo"));
                if (pGetPerformanceInfo) {
                    MY_PERFORMANCE_INFORMATION pinf{};
                    pinf.cb = sizeof(pinf);
                    if (pGetPerformanceInfo(&pinf, sizeof(pinf))) {
                        const unsigned long long page = (unsigned long long)pinf.PageSize;
                        BOOST_LOG_TRIVIAL(error) << __FUNCTION__
                            << " PerformanceInfo: CommitTotal=" << (unsigned long long)pinf.CommitTotal * page
                            << " CommitLimit=" << (unsigned long long)pinf.CommitLimit * page
                            << " CommitPeak=" << (unsigned long long)pinf.CommitPeak * page
                            << " PhysicalTotal=" << (unsigned long long)pinf.PhysicalTotal * page
                            << " PhysicalAvailable=" << (unsigned long long)pinf.PhysicalAvailable * page
                            << " SystemCache=" << (unsigned long long)pinf.SystemCache * page
                            << " KernelTotal=" << (unsigned long long)pinf.KernelTotal * page
                            << " KernelPaged=" << (unsigned long long)pinf.KernelPaged * page
                            << " KernelNonpaged=" << (unsigned long long)pinf.KernelNonpaged * page
                            << " ProcessCount=" << (unsigned long long)pinf.ProcessCount
                            << " HandleCount=" << (unsigned long long)pinf.HandleCount
                            << " ThreadCount=" << (unsigned long long)pinf.ThreadCount;
                    }
                }
                if (psapi_loaded) FreeLibrary(hPsapi);
             }
            
            // 追加：是否处于 Job（可能存在 Job 内存/工作集限制）
            BOOL in_job = FALSE;
            if (IsProcessInJob(GetCurrentProcess(), NULL, &in_job)) {
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << " InJob=" << (in_job ? 1 : 0);
            }
            // 追加：进程工作集限制（若被显式限制可在此体现）
            SIZE_T ws_min = 0, ws_max = 0; DWORD ws_flags = 0;
            if (GetProcessWorkingSetSizeEx(GetCurrentProcess(), &ws_min, &ws_max, &ws_flags)) {
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << " WorkingSetLimit: min=" << (unsigned long long)ws_min
                                         << " max=" << (unsigned long long)ws_max
                                         << " flags=0x" << std::hex << ws_flags << std::dec;
            }
            // 追加：捕获调用栈（地址+模块），帮助定位是谁在请求大块内存
            {
                HMODULE hK32 = GetModuleHandleW(L"kernel32.dll");
                typedef USHORT (WINAPI *PFN_RtlCaptureStackBackTrace)(ULONG, ULONG, PVOID*, PULONG);
                auto pBacktrace = reinterpret_cast<PFN_RtlCaptureStackBackTrace>(hK32 ? GetProcAddress(hK32, "RtlCaptureStackBackTrace") : nullptr);
                if (pBacktrace) {
                    void* frames[32] = { 0 };
                    USHORT captured = pBacktrace(0, (ULONG)_countof(frames), frames, nullptr);
                    for (USHORT i = 0; i < captured; ++i) {
                        void* addr = frames[i];
                        MEMORY_BASIC_INFORMATION mbi2{};
                        const char* mod_name = "";
                        char mod_path[260] = { 0 };
                        if (VirtualQuery(addr, &mbi2, sizeof(mbi2)) == sizeof(mbi2)) {
                            HMODULE hMod = (HMODULE)mbi2.AllocationBase;
                            DWORD n = GetModuleFileNameA(hMod, mod_path, (DWORD)sizeof(mod_path));
                            if (n > 0) mod_name = mod_path;
                        }
                        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << " Backtrace[" << i << "]: addr=" << addr
                                                 << " module=" << mod_name;
                    }
                }
            }
            // 地址空间遍历，估计可用区块与碎片程度
            SIZE_T largest_free = 0;
            SIZE_T free_regions = 0;
            SIZE_T total_free = 0;
            SIZE_T regions_scanned = 0;
            MEMORY_BASIC_INFORMATION mbi{};
            unsigned char* addr = nullptr;
            while (VirtualQuery(addr, &mbi, sizeof(mbi)) == sizeof(mbi)) {
                if (mbi.State == MEM_FREE) {
                    ++free_regions;
                    total_free += (SIZE_T)mbi.RegionSize;
                    if ((SIZE_T)mbi.RegionSize > largest_free) largest_free = (SIZE_T)mbi.RegionSize;
                }
                unsigned char* next = (unsigned char*)mbi.BaseAddress + mbi.RegionSize;
                if (next <= addr) break;
                addr = next;
                if (++regions_scanned > 100000) break; // 安全上限，避免极端情况下扫描过久
            }
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << " VAS: free_regions=" << (size_t)free_regions
                                     << " total_free=" << (size_t)total_free
                                     << " largest_free=" << (size_t)largest_free
                                     << " ptr_size=" << sizeof(void*);
            // 启发式判断：地址空间耗尽 / 碎片化
            if (largest_free < (SIZE_T)(16ull << 20)) {
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << " Heuristic: Address space exhaustion likely (largest_free < 16MB)";
            }
            if (free_regions > 1024 && largest_free * 4 < total_free) { 
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << " Heuristic: Severe VAS fragmentation suspected";
            }
#endif
            boost::log::core::get()->flush();
            already_in_handler = false; 
            int *p = nullptr;
            *p                 = 100;
            throw std::bad_alloc();
        });
#ifdef _MSC_VER
        // Install the sized CRT new-handler adapter AFTER the C++ handler so we can chain to it and capture size.
        g_cp_prev_new_handler_pnh = _set_new_handler(&g_cp_sized_new_handler_adapter);
#endif
        // Call the UTF8 main.
        return run_application(argc, argv_ptrs.data());
    }
}
#else /* _MSC_VER */
#if defined(__linux__) || defined(__LINUX__)
#ifdef USE_BREAKPAD
static bool dumpCallback(const google_breakpad::MinidumpDescriptor& descriptor,void* context, bool succeeded) {
                printf("Dump path: %s\n", descriptor.path());
		 if (succeeded) {
		     boost::filesystem::path oldPath(descriptor.path());
		     const std::string version_dir = Slic3r::data_directory_name();

             boost::filesystem::path dataPath(Slic3r::data_dir());
		     if (dataPath.empty()) {
			 if (const char* xdg_config_home = boost::nowide::getenv("XDG_CONFIG_HOME");
			     xdg_config_home != nullptr && *xdg_config_home != '\0') {
			     dataPath = boost::filesystem::path(xdg_config_home) / SLIC3R_APP_KEY;
			 } else if (const char* home = boost::nowide::getenv("HOME"); home != nullptr && *home != '\0') {
			     dataPath = boost::filesystem::path(home) / ".config" / SLIC3R_APP_KEY;
			 }
			 if (!dataPath.empty())
			     dataPath /= boost::filesystem::path(SLIC3R_APP_USE_FORDER) / version_dir;
		     }

		     boost::filesystem::path logPath = dataPath / "log";
		     boost::system::error_code directory_error;
		     if (dataPath.empty() ||
			 (!boost::filesystem::exists(logPath, directory_error) &&
			  !boost::filesystem::create_directories(logPath, directory_error))) {
			 std::fprintf(stderr,
			     "Breakpad: could not create crash log directory; keeping '%s': %s\n",
			     descriptor.path(), directory_error.message().c_str());
			 return succeeded;
		     }

		     boost::posix_time::ptime now = boost::posix_time::second_clock::local_time();
		     // 创建一个 time_facet 对象，用于自定义时间格式
		     boost::posix_time::time_facet* timeFacet = new boost::posix_time::time_facet();
		     std::stringstream ss;
		     // 设置时间格式为 yyyyMMDD_hhmmss
		     timeFacet->format("%Y%m%d_%H%M%S");
		     ss.imbue(std::locale(std::locale::classic(), timeFacet));
		     ss << now;

		     std::string timeStr = ss.str();
		     std::string processNameStr = timeStr + std::string("_") + SLIC3R_PROCESS_NAME + std::string("_") + CREALITYPRINT_VERSION + std::string("_") + PROJECT_VERSION_EXTRA + std::string(".dmp");
		     logPath /= processNameStr;

		     if (boost::filesystem::exists(oldPath)) {
			 // The dump and log directories may reside on different filesystems.
			 // Fall back to copy-and-remove when rename reports EXDEV.
			 boost::system::error_code move_error;
			 boost::filesystem::rename(oldPath, logPath, move_error);
			 if (move_error) {
			     boost::system::error_code copy_error;
			     boost::filesystem::copy_file(
			         oldPath, logPath,
			         boost::filesystem::copy_option::overwrite_if_exists,
			         copy_error);
			     if (copy_error) {
			         std::fprintf(stderr,
			             "Breakpad: could not move dump '%s' to '%s' "
			             "(rename: %s; copy: %s)\n",
			             oldPath.string().c_str(), logPath.string().c_str(),
			             move_error.message().c_str(), copy_error.message().c_str());
			         return succeeded;
			     }

			     boost::system::error_code remove_error;
			     boost::filesystem::remove(oldPath, remove_error);
			     if (remove_error) {
			         std::fprintf(stderr,
			             "Breakpad: copied dump but could not remove temporary "
			             "file '%s': %s\n",
			             oldPath.string().c_str(), remove_error.message().c_str());
			     }
			 }
			 // 获取当前可执行文件路径
			 char exePath[PATH_MAX];
			 ssize_t len = readlink("/proc/self/exe", exePath, sizeof(exePath) - 1);
			 if (len != -1) {
			     exePath[len] = '\0';
			     std::string command = std::string(exePath) + " \"minidump://file=" + logPath.string() + "\"";
			     // 使用fork和exec启动新进程
			     pid_t pid = fork();
			     if (pid == 0) {
				 // 子进程
				 execl("/bin/sh", "sh", "-c", command.c_str(), (char*)NULL);
				 _exit(1); // 如果exec失败
			     } else if (pid > 0) {
				 // 父进程继续执行
			     }
			 }
		     }
		     
		     BOOST_LOG_TRIVIAL(info) << "MiniDump succeeded: " << descriptor.path();
		 } else {
		     BOOST_LOG_TRIVIAL(error) << "MiniDump failed: " << descriptor.path();
		 }
                return succeeded;
            }
#endif
#endif
int main(int argc, char **argv)
{
   BOOST_LOG_TRIVIAL(error) << "main start";
#ifdef __linux__
   BOOST_LOG_TRIVIAL(error) << "main __linux__";
    //setenv("WEBKIT_DISABLE_COMPOSITING_MODE", "1", 1);
#endif
    
    boost::filesystem::path   tempPath = boost::filesystem::path(wxFileName::GetTempDir().ToStdString());
    if (argc == 2 && boost::starts_with(std::string(argv[1]), "minidump://file=")) {
	 // 处理崩溃报告参数，直接启动GUI应用程序
	 return run_application(argc, argv);
    }else
    {
       BOOST_LOG_TRIVIAL(error) << "main check linux";
       #if defined(__linux__) || defined(__LINUX__)
             #ifdef USE_BREAKPAD
                BOOST_LOG_TRIVIAL(error) << "main google_breakpad init";
                google_breakpad::MinidumpDescriptor descriptor("/tmp");
                google_breakpad::ExceptionHandler eh(descriptor, NULL, dumpCallback, NULL, true, -1);
                BOOST_LOG_TRIVIAL(error) << "main google_breakpad init finished";
                return run_application(argc, argv);
            #endif
        #endif
    }
    
    return run_application(argc, argv);
}
#endif /* _MSC_VER */
