macro(__cgal_find_package package dir)
	set(${dir} ${CGAL_INCLUDE_DIRS}/${package}) 
endmacro()

macro(__cgal_include_package package)
	include_directories(${CGAL_INCLUDE_DIRS}/${package})
endmacro()

macro(__cgal_include_common_packages)
	__cgal_include_package(Kernel_23)
	__cgal_include_package(Cartesian_kernel)
	__cgal_include_package(Filtered_kernel)
	__cgal_include_package(STL_Extension)
	__cgal_include_package(Number_types)
	__cgal_include_package(Installation)
	__cgal_include_package(Profiling_tools)
	__cgal_include_package(Stream_support)
	__cgal_include_package(Algebraic_foundations)
	__cgal_include_package(Interval_support)
	__cgal_include_package(Modular_arithmetic)
	__cgal_include_package(Distance_2)
	__cgal_include_package(Distance_3)
	__cgal_include_package(Intersections_2)
	__cgal_include_package(Intersections_3)
	__cgal_include_package(Homogeneous_kernel)
	__cgal_include_package(Kernel_d)
	__cgal_include_package(Arithmetic_kernel)
	__cgal_include_package(Circulator)
	__cgal_include_package(HalfedgeDS)
	__cgal_include_package(Hash_map)
	__cgal_include_package(BGL)
	__cgal_include_package(Property_map)
endmacro()

__cc_find(CGAL)
