
set(DESKTOP_LINK_NAME "Creality Print")
string(REPLACE " " "_" CPACK_FILE_NAME_NO_SPACES "${DESKTOP_LINK_NAME}")
macro(prepareNSIS_Link linkName appName params)
  #prepare start menu links
  LIST(APPEND CPACK_NSIS_CREATE_ICONS_EXTRA " CreateShortCut '$SMPROGRAMS\\\\$STARTMENU_FOLDER\\\\${linkName}.lnk' '$INSTDIR\\\\${appName}.exe' '${params}'")
  LIST(APPEND CPACK_NSIS_DELETE_ICONS_EXTRA " Delete '$SMPROGRAMS\\\\$START_MENU\\\\${linkName}.lnk'")

  #prepare desktop links
  LIST(APPEND CPACK_NSIS_CREATE_ICONS_EXTRA " CreateShortCut '$DESKTOP\\\\${linkName}.lnk' '$INSTDIR\\\\${appName}.exe' '${params}'")
  LIST(APPEND CPACK_NSIS_DELETE_ICONS_EXTRA " Delete '$DESKTOP\\\\${linkName}.lnk'")

  SET(CPACK_SOFEWARE_PROCESS_NAME "${appName}.exe")
  LIST(APPEND CPACK_ONINIT_DELETE_DESTOP_LINK "Delete '$DESKTOP\\\\${linkName}.lnk'")
endmacro()

if(${PROJECT_VERSION_EXTRA} STREQUAL "Release")
    set(CPACK_NSIS_PACKAGE_NAME "${DESKTOP_LINK_NAME}")
    set(CPACK_NSIS_DISPLAY_NAME "${DESKTOP_LINK_NAME} ${CREALITYPRINT_VERSION_MAJOR}.${CREALITYPRINT_VERSION_MINOR}")
else()
    set(CPACK_NSIS_PACKAGE_NAME "${DESKTOP_LINK_NAME} ${CREALITYPRINT_VERSION_MAJOR}.${CREALITYPRINT_VERSION_MINOR} ${PROJECT_VERSION_EXTRA}")
    set(CPACK_NSIS_DISPLAY_NAME "${DESKTOP_LINK_NAME} ${CREALITYPRINT_VERSION_MAJOR}.${CREALITYPRINT_VERSION_MINOR} ${PROJECT_VERSION_EXTRA}")
endif()
if(${PROJECT_VERSION_EXTRA} STREQUAL "Release")
    set(CPACK_NSIS_PROJECT_NAME "${PROJECT_NAME}-${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}")    
else()
    set(CPACK_NSIS_PROJECT_NAME "${PROJECT_NAME}-${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}-${PROJECT_VERSION_EXTRA}")
endif()
set(PROGRAM_CMD "$INSTDIR\\\\${PROCESS_NAME}.exe  %1")

set(PRODUCT_DIR_REGKEY "Software\\\\Microsoft\\\\Windows\\\\CurrentVersion\\\\App Paths\\\\dpinst-x86.exe")
set (CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
#LIST(APPEND CPACK_NSIS_EXTRA_PREINSTALL_COMMANDS "\${nsProcess::KillProcess} '${PROJECT_NAME}' $R0")
LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "SetShellVarContext all")
LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr HKLM '${PRODUCT_DIR_REGKEY}' '' '$INSTDIR\\\\${PROJECT_NAME}.exe'")
LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr HKCR '.stl' '' 'stl_cxsw'")
LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS " WriteRegStr HKCR '.gcode' '' 'gcode_cxsw'")
LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS " WriteRegStr HKCR '.3mf' '' '3mf_cxsw'")
LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS " WriteRegStr HKCR '.cxprj' '' 'cxprj_cxsw'")
##add stl
LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr HKCR 'stl_cxsw' '' 'model (.stl)'")
LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr HKCR 'stl_cxsw\\\\DefaultIcon' '' '$INSTDIR\\\\${PROJECT_NAME}.exe,1'")
# LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr HKCR 'stl_cxsw\\\\shell\\\\open\\\\command' '' '${PROGRAM_CMD}'")

##add gcode
LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr HKCR 'gcode_cxsw' '' 'project (.gcode)'")
LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr HKCR 'gcode_cxsw\\\\DefaultIcon' '' '$INSTDIR\\\\${PROJECT_NAME}.exe,2'")
# LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr HKCR 'gcode_cxsw\\\\shell\\\\open\\\\command' '' '${PROGRAM_CMD}'")

##add 3mf
LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr HKCR '3mf_cxsw' '' 'project (.3mf)'")
LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr HKCR '3mf_cxsw\\\\DefaultIcon' '' '$INSTDIR\\\\${PROJECT_NAME}.exe,3'")
# LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr HKCR '3mf_cxsw\\\\shell\\\\open\\\\command' '' '${PROGRAM_CMD}'")

##add cx3d
LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr HKCR 'cxprj_cxsw' '' 'project (.cxprj)'")
LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr HKCR 'cxprj_cxsw\\\\DefaultIcon' '' '$INSTDIR\\\\${PROJECT_NAME}.exe,4'")
# LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr HKCR 'cxprj_cxsw\\\\shell\\\\open\\\\command' '' '${PROGRAM_CMD}'")

set (CPACK_PACKAGE_NAME "${PROCESS_NAME}")
set (CPACK_PACKAGE_VENDOR "${VENDOR_NAME}")
set (CPACK_PACKAGE_VERSION_MAJOR "${CREALITYPRINT_VERSION_MAJOR}")
set (CPACK_PACKAGE_VERSION_MINOR "${CREALITYPRINT_VERSION_MINOR}")
set (CPACK_PACKAGE_VERSION_PATCH "${CREALITYPRINT_VERSION_PATCH}")
set (CPACK_PACKAGE_FILE_NAME "${PROCESS_NAME}_${CREALITYPRINT_VERSION}_${PROJECT_VERSION_EXTRA}")
set (CPACK_PACKAGE_DESCRIPTION_SUMMARY "Creality Print is an open source slicer for FDM printers")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "${VENDOR_NAME}\\${CPACK_NSIS_DISPLAY_NAME}")
SET(CPACK_PACKAGE_UNICODE "Unicode True") #Multilingual garbled
SET(CPACK_NSIS_MUI_ICON "${CMAKE_SOURCE_DIR}/package/icon/NSIS.ico")
SET(CPACK_PACKAGE_ICON "${CMAKE_SOURCE_DIR}/package/icon\\\\NSISHeader.ico")
set (CPACK_NSIS_MUI_UNIICON "${CPACK_PACKAGE_ICON}")
set(CPACK_NSIS_MUI_WELCOMEFINISHPAGE_BITMAP ${CMAKE_SOURCE_DIR}/package/icon\\\\creality_banner_nsis.bmp)    # note: fails with forward '/'
set(CPACK_NSIS_MUI_UNWELCOMEFINISHPAGE_BITMAP ${CMAKE_SOURCE_DIR}/package/icon\\\\creality_banner_nsis.bmp)
# LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "
#     CreateShortCut \\\"$DESKTOP\\\\CrealityPrint.lnk\\\" \\\"$INSTDIR\\\\CrealityPrint.exe\\\"
# ")
#去除图标的缓存
# LIST(APPEND CPACK_NSIS_EXTRA_INSTALL_COMMANDS "System::Call 'Shell32::SHChangeNotify(i 0x8000000, i 0, i 0, i 0)'")

prepareNSIS_Link("${CPACK_NSIS_DISPLAY_NAME}" "${PROCESS_NAME}" "")
STRING (REPLACE ";" "\n" CPACK_NSIS_CREATE_ICONS_EXTRA "${CPACK_NSIS_CREATE_ICONS_EXTRA}")
STRING (REPLACE ";" "\n" CPACK_NSIS_DELETE_ICONS_EXTRA "${CPACK_NSIS_DELETE_ICONS_EXTRA}")
STRING (REPLACE ";" "\n" CPACK_NSIS_EXTRA_INSTALL_COMMANDS "${CPACK_NSIS_EXTRA_INSTALL_COMMANDS}")
# set (CPACK_PACKAGE_CHECKSUM SHA256)
set (CPACK_PACKAGE_INSTALL_REGISTRY_KEY "CrealityPrint")

set (CPACK_NSIS_EXECUTABLES_DIRECTORY ".")
# set (CPACK_NSIS_MODIFY_PATH "ON")
set(CPACK_PACKAGE_EXECUTABLES "CrealityPrint;CrealityPrint")
set(CPACK_CREATE_DESKTOP_LINKS "${PROCESS_NAME}")
#set (CPACK_RESOURCE_FILE_LICENSE ${CMAKE_SOURCE_DIR}/LICENSE.txt) # must also include in install command
set(LICENSE_FILE "license.rtf")
set(LICENSE_FILE_EN "license_en.rtf")
set(LICENSE_FILE_TD "license.rtf")
SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/${LICENSE_FILE}")
SET(CPACK_RESOURCE_FILE_LICENSE_EN "${CMAKE_SOURCE_DIR}/${LICENSE_FILE_EN}")
SET(CPACK_RESOURCE_FILE_LICENSE_TD "${CMAKE_SOURCE_DIR}/${LICENSE_FILE_TD}")
SET(CPACK_NSIS_INSTALLED_ICON_NAME "${PROCESS_NAME}${CMAKE_EXECUTABLE_SUFFIX}")
set(CPACK_NSIS_MUI_FINISHPAGE_RUN "${CPACK_NSIS_INSTALLED_ICON_NAME}")
#unstall
LIST(APPEND CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "DeleteRegKey HKCR '.stl'")
LIST(APPEND CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "DeleteRegKey HKCR '.obj'")
LIST(APPEND CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "DeleteRegKey HKCR '.cxprj'")
LIST(APPEND CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "DeleteRegKey HKCR '.gcode'")
LIST(APPEND CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS "DeleteRegKey HKCR '.3mf'")

set(CPACK_NSIS_INSTALLER_MUI_FINISHPAGE_RUN_CODE "!define MUI_FINISHPAGE_RUN \\\"$WINDIR\\\\explorer.exe\\\"\n!define MUI_FINISHPAGE_RUN_PARAMETERS \\\"$INSTDIR\\\\${PROJECT_NAME}.exe\\\"")

set(CPACK_WIX_UPGRADE_GUID "058245e8-20e0-4a95-9ab7-1acfe17ad511")

# configure_file(${CMAKE_SOURCE_DIR}/package/installer.nsi ${CMAKE_BINARY_DIR} COPYONLY)
set(CPACK_WEBVIEW2_NAME "MicrosoftEdgeWebView2RuntimeInstallerX64.exe")
set(CPACK_VCREDIST_X64_NAME "vcredist_x64.exe")
# set(CPACK_NSIS_EXTRA_SCRIPT "${CMAKE_BINARY_DIR}/installer.nsi")
set(CPACK_GENERATOR NSIS)
include(CPack)
